### ISSUE TITLE
Bug Fix: plot_graph_route throws 'NoneType' object has no attribute 'values'

### ISSUE THREAD

**Issue by trebsirk** [gboeing/osmnx#300] opened 2019-06-11 02:20 UTC
I tried to run `ox.plot_graph_route` and it's breaking when edges do not have an associated attributes dict. 

<details>
I'm using the docker image gboeing/osmnx running on Mac OS X. 
</details>

I think the solution here is to change line 470 of https://github.com/gboeing/osmnx/blob/master/osmnx/plot.py from
```python
data = min(G.get_edge_data(u, v).values(), key=lambda x: x['length'])
```
to 
```python
data = min(G.get_edge_data(u, v, default={0:{'length':0}}).values(), key=lambda x: x['length'])
```

**Comment by gboeing** [comment] 2019-06-11 11:57
Thanks @trebsirk. Can you provide a use case for this? Under what circumstances would graph edges not have their `data` dicts?

**Comment by trebsirk** [comment] 2019-06-11 22:34
I am trying to make a route, but there are duplicate adjacent nodes, which means there is an edge (u, v) where u == v. I'm trying to plot a route of breadcrumbs based on driving data where there are delays at certain nodes. 
Here are example breadcrumbs, given as tuples of (node, time):
(49392, 0)
(5932, 1)
(5932, 2)
(93839, 3)

**Comment by gboeing** [comment] 2019-06-11 22:56
Can you provide an MWE so I can reproduce?

**Comment by trebsirk** [comment] 2019-06-11 23:37
I ran this from a jupyter notebook. 

```bash
docker run --rm -p 8888:8888 -e JUPYTER_ENABLE_LAB=yes -v "$PWD":/home/jovyan/work gboeing/osmnx
```

```python
import osmnx as ox
from random import choice, choices

G = ox.graph_from_address('N. Sicily Pl., Chandler, Arizona', distance=100, network_type='drive')
route = []
while len(route) < 3:
    n1, n2 = choices(population = list(G.nodes()), k = 2)
    route = nx.shortest_path(G, n1, n2)
#route.append(route[-1])
print('route: {}'.format(route))
ox.plot_graph_route(G, route)
```

**Comment by gboeing** [comment] 2019-06-12 13:10
You're not passing a valid route to `plot_graph_route`. You said:

>  it's breaking when edges do not have an associated attributes dict

but it's breaking because there you're telling it to look for an edge that doesn't exist. When you run `route.append(route[-1])` you are duplicating the final node in the route again at the end of the route. Unless there is a self-loop in the graph that links that node to itself, then there is no valid edge there to traverse. See [here](https://en.wikipedia.org/wiki/Path_(graph_theory)):

> In graph theory, a path in a graph is a finite or infinite sequence of edges which joins a sequence of vertices which, by most definitions, are all distinct (and since the vertices are distinct, so are the edges).

OSMnx does not require that they all be distinct, but it does require that the list of nodes you provide as the route do define a valid path (i.e., that they correspond pairwise to a real sequence of edges).

**Comment by trebsirk** [comment] 2019-06-12 14:18
Yes, I realize it's not technically a route due to repeated notes, but having the default dict will obviate the need for preprocessing a certain class of real-world data. Is there a good reason not to have the default dict passed to `get_edge_data`?

**Comment by gboeing** [comment] 2019-10-02 17:25
As no one else has weighed in on this feature or requested in a few months, I'm going to close it for now, but can always reopen should the need arise.

**Closed by gboeing** 2019-10-02 17:25 UTC
Labels: enhancement
