### ISSUE TITLE
graph_from_xml not connecting network

### ISSUE THREAD

**Issue by shriv** [gboeing/osmnx#558] opened 2020-09-15 04:28 UTC
This "bug" report is stretching the functionality of osmnx but here goes. My use case is taking a shapefile / geojson of the "official" rail network for NZ, converting to `.osm` format and then reading into `osmnx`. It is worth noting that getting the rail infrastructure with `osmnx` does work. I've pursued this option of reading data from a shapefile because it seems useful to see if shapefiles can be made into routable networks. Public sector in NZ serves a lot of infrastructure data via ArcGIS hub and the shapefile is a common format for open data of transport infrastructure. 

## Input
[Shapefile data](https://services6.arcgis.com/eqX2HMCD3H8MUs6Q/arcgis/rest/services/KiwiRailTrack/FeatureServer/0/query?where=Type%20%3D%20%27MAIN%20LEFT%27&outFields=*&outSR=4326&f=json)

## Input conversion
- Using `ogr2osm` to convert from `geojson` to `.osm`. [ogr2osm](https://github.com/pnorman/ogr2osm)
```
 python ogr2osm.py main_left_filtered.geojson
```

## Reading into `osmnx`
- Saved `.osm` read with `graph_with_xml`
```
rail_net_ox = ox.graph_from_xml("data/main_left_filtered.osm", simplify=True, retain_all=True)
```

## What works
- The graph seems to be read in sensibly though IDs are negative for some reason! I suspect this is a 'feature' of the `ogr2osm` conversion. 

![image](https://user-images.githubusercontent.com/3827179/93164757-6c14ff00-f76e-11ea-8a24-2e196e6b6e71.png)

## What doesn't work
- I cannot route on this network. Some of the issues seem to be because one of the main trunk lines doesn't make it into the largest connected component for the North Island. I'm not sure why this happens? I've checked the spatial connectivity and there are no obvious gaps!

![image](https://user-images.githubusercontent.com/3827179/93165042-1c830300-f76f-11ea-8929-466c12cbf71b.png)

## Environment
- Python 3.6.10
- osmnx 0.15.1

Any suggestions  / advice would be super helpful! 

Thanks a lot! 
Shrividya

**Comment by gboeing** [comment] 2020-09-16 16:56
> I cannot route on this network. Some of the issues seem to be because one of the main trunk lines doesn't make it into the largest connected component for the North Island.

What specific origin/destination pairs are unsolvable? Try digging into your graph and identifying the point at which the main trunk line disconnects from the North Island's largest connected component. What specifically is missing there? Is there an specific edge missing? If so, what is that way's OSM ID? Can you find it in your .osm file?

Given the reliance on a 3rd party tool to convert geojson -> .osm XML, it's hard to guess where the problem might be. If you can reproduce the problem with an official .osm extract then I'd guess it's a bug in OSMnx. Otherwise, I'd guess it's not... but let me know what your investigation into the above questions uncovers and I can take a further look.

**Comment by gboeing** [comment] 2020-09-16 17:16
The problem appears to be the connectivity of this red edge here:

![Screenshot from 2020-09-16 10-08-45](https://user-images.githubusercontent.com/4977197/93369837-cbbde980-f804-11ea-8443-7dbf71154b7c.png)

It's all one edge. That graph component that branches off of it to the east is not connected: the node in the middle of it (ID "-66793", assigned by the converter tool but meaningless as it's not a real OSM ID) is not part of the edge I've highlighted in red. Hence you cannot route anything out to that eastern branch.

**Comment by shriv** [comment] 2020-09-21 03:52
Hiya,
Thanks so much for your quick response! I had a look at that edge. I wasn't able to see the disconnectivity though. How were you able to zoom in so far? In any case, do you think this is because of the `ogr2osm` tool? Afaik, the tool doesn't create OSMIDs, it just creates unique IDs. 

I don't think the original network would have been disconnected so is there some reason why `osmnx` is not able to connect this edge? It seems to have connected the rest of the North Island rail network correctly.. 

Thanks again! 
Shrividya

**Comment by gboeing** [comment] 2020-09-21 03:58
I just saved the graph to a geopackage, opened in QGIS, and explored around. If you track that node down on OSM and can pinpoint OSMnx as breaking this, we can reopen. But for now I'm going to close this as it looks like an issue with the input data.

**Closed by gboeing** 2020-09-21 03:58 UTC
Labels: bug

**Comment by 212782435** [comment] 2024-08-22 08:33
I am facing out of memory error everytime I try to load an OSM XML file using below:
G = ox.graph.graph_from_xml(osm_file_path, bidirectional=False, simplify=True, retain_all=True, encoding='utf-8')
This mainly happens for bigger regions - anything bigger than 500MB - is there any filter available to be used to optimize the graph load

**Comment by e4eklavya** [comment] 2024-08-22 08:48
I am trying to use the graph_from_xml option to load data from osm files which was downloaded and converted from the geofabrik site for various countries - but I am constantly facing error while trying to load larger subregions larger than 500MB

few samples include:
north-america-mexico-latest.osm.pbf converted to north-america-mexico-latest.osm
north-america-canada-alberta-latest.osm.pbf converted to north-america-canada-alberta-latest.osm
asia-vietnam-latest.osm.pbf converted to asia-vietnam-latest.osm

However in cases where the file size is less than 300 MB I am able to load the graph using graph_from_xml

Below is the code snippet of my try statement:
    try:
        print(f"Starting OSM graph creation for {country_name}")
       
        # Create graph from OSM XML file
        G = ox.graph.graph_from_xml(osm_file_path, bidirectional=False, simplify=True, retain_all=True, encoding='utf-8')


FYI I have also tried to filter out on the tags - but still facing out of memory error - please let me know if there is a way to optimize the graph_from_xml call to filter the data to be loaded or any other inputs
