### ISSUE TITLE
Error with plot.get_node_colors_by_attr() function

### ISSUE THREAD

**Issue by pthangeda** [gboeing/osmnx#515] opened 2020-06-28 03:22 UTC
#### Problem description
Function ox.plot.get_node_colors_by_attr() raises ValueError when the node attribute considered for plotting has a highly biased distribution. This error comes down to an issue with the pd.qcut used to create bins. The function raises ValueError when edges are non unique and a quick fix would be to drop duplicate edges. 

#### What operating system, Python version, and OSMnx version are you using?
Ubuntu 18.04 and osmnx version 0.14.1

<details>
Here is the error message:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-81-e52a5c62776f> in <module>
----> 1 nc1 = ox.plot.get_node_colors_by_attr(G, 'pop_score_block', cmap='plasma')
      2 fig1, ax1 = ox.plot_graph(G, node_color=nc1, node_size=20, node_zorder=2,
      3                         edge_linewidth=2, edge_color='#333333', bgcolor='k')

~/miniconda3/envs/temp/lib/python3.6/site-packages/osmnx/plot.py in get_node_colors_by_attr(G, attr, num_bins, cmap, start, stop, na_color)
    214     bin_labels = range(num_bins)
    215     attr_values = pd.Series([data[attr] for node, data in G.nodes(data=True)])
--> 216     cats = pd.qcut(x=attr_values, q=num_bins, labels=bin_labels)
    217     colors = get_colors(num_bins, cmap, start, stop)
    218     node_colors = [colors[int(cat)] if pd.notnull(cat) else na_color for cat in cats]

~/miniconda3/envs/temp/lib/python3.6/site-packages/pandas/core/reshape/tile.py in qcut(x, q, labels, retbins, precision, duplicates)
    346         include_lowest=True,
    347         dtype=dtype,
--> 348         duplicates=duplicates,
    349     )
    350 

~/miniconda3/envs/temp/lib/python3.6/site-packages/pandas/core/reshape/tile.py in _bins_to_cuts(x, bins, right, labels, precision, include_lowest, dtype, duplicates)
    379         if duplicates == "raise":
    380             raise ValueError(
--> 381                 f"Bin edges must be unique: {repr(bins)}.\n"
    382                 f"You can drop duplicate edges by setting the 'duplicates' kwarg"
    383             )

ValueError: Bin edges must be unique: array([  0.        ,   0.        ,   0.        , ..., 769.40659062,
       792.8       , 792.8       ]).
You can drop duplicate edges by setting the 'duplicates' kwarg

</details>

**Comment by gboeing** [comment] 2020-06-28 05:31
Thanks @pthangeda. There have been major changes to the plot module and color functions since that release. Does this remain an issue in the current master branch?

**Comment by gboeing** [comment] 2020-06-29 17:48
Without a reproducible code snippet, I cannot reproduce exactly what you're seeing. But this should be fixed in the forthcoming release. Here's an example.

With v0.14.1:

```python
import osmnx as ox
ox.config(use_cache=True)
print(ox.__version__)  # 0.14.1
G = ox.graph_from_place('Piedmont, CA, USA', network_type='drive')
G = ox.add_edge_speeds(G)
ec = ox.plot.get_edge_colors_by_attr(G, 'speed_kph')  # THROWS AN ERROR
# ValueError: Bin edges must be unique...
```

With v0.15.0:

```python
import osmnx as ox
ox.config(use_cache=True)
print(ox.__version__)  # 0.15.0
G = ox.graph_from_place('Piedmont, CA, USA', network_type='drive')
G = ox.add_edge_speeds(G)
ec = ox.plot.get_edge_colors_by_attr(G, 'speed_kph')  # WORKS SUCCESSFULLY
```

**Closed by gboeing** 2020-06-29 17:48 UTC
