### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by tetekos** [gboeing/osmnx#17] opened 2016-12-12 16:00 UTC
Hello all,

I am new here thus excuse me if I am asking something simple.

I have been trying to get osmnx going with that:
import osmnx as ox
city = ox.gdf_from_place('Berkeley, CA')
ox.plot_shape(ox.project_gdf(city))

But I am getting this output error all the time:
**[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)**

Please could you suggest any solutions cause the ones I have seen so far are not working.

Thanks a lot.

**Comment by gboeing** [comment] 2016-12-12 20:11
What is your OS, architecture, Python version, OSMnx version, etc? Are your Python packages up-to-date, especially `requests` and `openssl`?

**Comment by gboeing** [comment] 2016-12-19 19:38
@tetekos checking back once again on this open issue... see previous comment.

**Comment by gboeing** [comment] 2017-01-10 06:23
Closing this issue now. If this problem crops up again, please add additional details and we can chase it down.

**Closed by gboeing** 2017-01-10 06:23 UTC

**Comment by MonoPaul** [comment] 2017-05-05 20:57
Getting that same issue here - client is using a custom SSL certificate.
I can connect using requests directly by either pointing to the local cert, or by passing the parameter cert=False to the get request.
Any chance you can add a parameter that gets passed to general https requests ?

**Comment by MonoPaul** [comment] 2017-05-05 21:04
Ah - issue occurs on Win 7 & Jupyter running on Debian Mint, on both python 2.7.13 & 3.5.
I am using OSMnx v 0.5, and requests & openssl are all up to date :-)

**Comment by gboeing** [comment] 2017-05-05 21:49
@MonoPaul can you provide me a working example of code to reproduce this, plus the error's full traceback message?

**Comment by MonoPaul** [comment] 2017-05-06 15:42
The full traceback'll have to wait till Monday - my home SSL works just fine. The code I used was simply a regular request : 
import osmnx as ox
G = ox.graph_from_place('Manhattan, New York, USA')
I'm guessing that works under normal circumstances - what I'd be requesting would be more of a feature request than a bug report : an option to either pass a specific SSL cert or disable SSL (ie passing the cert=('/path/to/cert') in the requests.get)
Let me know if you'd rather have me branch instead ;-)

**Comment by gboeing** [comment] 2017-05-06 19:40
Thanks for that info!

Before we make changes to the OSMnx code, I'd like to know more about why this error is occurring. I have not been able to reproduce it on Windows or Linux with Python 2.7, 3.5, or 3.6. And it looks like it's happening inconsistently from one computer to another for you? Is this something platform-specific? And why? Is it happening inside `requests`, or where? As I haven't been able to reproduce it and haven't seen a full traceback, it's hard to know what is going on and why.

What is the use case for disabling SSL or specifying a local certificate file? If it's just to get OSMnx working in the face of this CERTIFICATE_VERIFY_FAILED error, I'd rather first solve the error so certification verification succeeds, rather than add the ability to disable SSL. The latter seems like a symptom rather than the problem.

That said, if there's a use case for this I'm totally open to a PR.

**Comment by MonoPaul** [comment] 2017-05-06 20:52
I absolutely agree with the bit about having the SSL verification work instead of just disabling it overall !
In this case however, the issue happens on my client's network, where they use an in-house issued certificate instead of one from a standard provider - hence the need to point to it (or, worse case, disable it). I absolutely don't think it's (politically) feasable to convince them to change their ways at this time.

AFAIK, the verification usually is done inside `request` (or further down, in `urllib3`), and the use of the standard (local) CAs is permitted when using these libs directly. That being said, permitting local CAs - even if disabled by default - remains a desing decision which I'll leave in your hands :-)

As I said, I'll provide the full traceback on Monday - at which point I'll also have time to work on an eventual pull request if required.

**Comment by gboeing** [comment] 2017-05-06 21:14
Thanks! That use case makes sense.

To add this functionality I see three options. 1) add a new `cert` argument to all functions that use `requests`, and propagate this argument to all the functions that use that function, and to all the functions that use those functions, etc. 2) add a new global config to allow users to set the path to a local certificate, then modify all functions that use `requests` to see if this config value has been set or not. The main issue for me is that I have no way to test any of that functionality, as I don't have a local certificate. 3) add a new `disable_ssl` global config and just have all the requests use its value. Option 1 seems cleanest to me but difficult for me test.

**Comment by jag-123** [comment] 2017-06-02 20:59
I'm also having this problem and I'm not sure, but it might be due to the fact that I'm using a proxy server. I  would appreciate an option to disable SSL.

**Comment by JFloresX** [comment] 2017-09-11 17:53
Hey
I have also been trying to get osmnx going with:

import osmnx as ox
city = ox.gdf_from_place('Berkeley, CA')
ox.plot_shape(ox.project_gdf(city))

But I was getting the:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

I ran the following commands:
conda config --set ssl_verify false
conda update conda requests cryptography pyopenssl
conda config --remove-key ssl_verify

However I am getting an SSL relate error. Not sure where to go form here.  

SSLError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?format=json&limit=1&dedupe=0&polygon_geojson=1&q=Berkeley%2C+CA (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))

Conda info below:

![image](https://user-images.githubusercontent.com/22304142/30288945-7d0cbcaa-96f8-11e7-8cc4-641bce7ca6f2.png)

**Comment by gboeing** [comment] 2017-09-11 17:55
@JFloresX can you tell us more about your working environment? Do you need to use a local certificate?

**Comment by JFloresX** [comment] 2017-09-11 18:05
@gboeing A local certificate is not necessary. Not sure what you mean by the working environment. I am running python 2.7, on the anaconda distribution.

**Comment by gboeing** [comment] 2017-09-14 03:28
@JFloresX I'm not able to reproduce your error... can you tell me anything more about your network or computer system? Anything that might give a clue as to why your certificate situation might be different?

**Comment by o1lo01ol1o** [comment] 2018-07-06 09:36
I'm also encountering this error.  `requests` `pyopenssl` `cryptography` and `certifi` are all most recent versions for python 3.6.  `OpenSSL` is the most recent formula from `homebrew` and I'm on Sierra 10.12.6.  The error occurs over public internet and over public internet via our private vpn tunnel.

stacktrace: https://gist.github.com/o1lo01ol1o/31a45601191a65bf5db01a43866f3416

   Is there a workaround?

**Comment by Wenping-Cui** [comment] 2021-06-30 22:49
I solved this issue by synchronizing the system clock.

**Comment by gboeing** [comment] 2021-08-16 16:12
You can now point to a local certificate file or override requests' parameters like auth, cert, verify, and proxies. See #745.
