### ISSUE TITLE
Polygon fails to evaluate in geometries_from_point

### ISSUE THREAD

**Issue by TMorville** [gboeing/osmnx#673] opened 2021-03-12 10:14 UTC
**Problem description**
  - What did you do?
```
import osmnx as ox
ox.geometries.geometries_from_point((55.676098, 12.568337), tags={'amenity': True}, dist=250)
```
  - What did you expect to happen?
Return of GDF
  - And what actually happened instead?
```
IllegalArgumentException: Argument must be Polygonal or LinearRing
---------------------------------------------------------------------------
PredicateError                            Traceback (most recent call last)
<ipython-input-128-8cd4b5d3eac7> in <module>
----> 1 ox.geometries.geometries_from_point((55.676098, 12.568337), tags={'amenity': True}, dist=250)

/usr/local/anaconda3/envs/casa/lib/python3.8/site-packages/osmnx/geometries.py in geometries_from_point(center_point, tags, dist)
    114 
    115     # create GeoDataFrame of geometries within this polygon
--> 116     gdf = geometries_from_polygon(polygon, tags)
    117 
    118     return gdf

/usr/local/anaconda3/envs/casa/lib/python3.8/site-packages/osmnx/geometries.py in geometries_from_polygon(polygon, tags)
    250     """
    251     # verify that the geometry is valid and a Polygon/MultiPolygon
--> 252     if not polygon.is_valid:
    253         raise ValueError("The geometry of `polygon` is invalid")
    254     if not isinstance(polygon, (Polygon, MultiPolygon)):

/usr/local/anaconda3/envs/casa/lib/python3.8/site-packages/shapely/geometry/base.py in is_valid(self)
    729         """True if the geometry is valid (definition depends on sub-class),
    730         else False"""
--> 731         return bool(self.impl['is_valid'](self))
    732 
    733     # Binary predicates

/usr/local/anaconda3/envs/casa/lib/python3.8/site-packages/shapely/predicates.py in __call__(self, this)
     23     def __call__(self, this):
     24         self._validate(this)
---> 25         return self.fn(this._geom)

/usr/local/anaconda3/envs/casa/lib/python3.8/site-packages/shapely/geos.py in errcheck_predicate(result, func, argtuple)
    582     """Result is 2 on exception, 1 on True, 0 on False"""
    583     if result == 2:
--> 584         raise PredicateError("Failed to evaluate %s" % repr(func))
    585     return result
    586 

PredicateError: Failed to evaluate <_FuncPtr object at 0x7fe4d05987c0>
```

**Environment information**
  - What operating system are you using? **OSx Big Sur (11.2.1)**
  - What Python version are you using? **3.8.5**
  - What OSMnx version are you using? **1.0.1**
  - Provide a complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output between the two "details" tags below)

<details>
```
# Name                    Version                   Build  Channel
_py-xgboost-mutex         2.0                       cpu_0
absl-py                   0.11.0                   pypi_0    pypi
appnope                   0.1.0                 py38_1001
argon2-cffi               20.1.0           py38haf1e3a3_1
astor                     0.8.1                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
async_generator           1.10                       py_0
attrs                     20.3.0             pyhd3eb1b0_0
backcall                  0.2.0                      py_0
bayesian-optimization     1.1.0                      py_0    conda-forge
blas                      1.0                         mkl
bleach                    3.2.1                      py_0
boost-cpp                 1.74.0               h43a636a_2    conda-forge
branca                    0.4.2              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py38h9ed2024_1003
bzip2                     1.0.8                hc929b4f_4    conda-forge
c-ares                    1.17.1               h0d85af4_1    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
cachetools                4.1.1                    pypi_0    pypi
cairo                     1.16.0            h4ec454a_1007    conda-forge
catboost                  0.24.3           py38h50d1736_0    conda-forge
category_encoders         2.2.2                      py_0    conda-forge
certifi                   2020.12.5        py38h50d1736_1    conda-forge
cffi                      1.14.3           py38h2125817_2
cfitsio                   3.470                h422484a_7    conda-forge
chardet                   3.0.4           py38hecd8cb5_1003
click                     7.1.2                      py_0
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.0                    pypi_0    pypi
cryptography              3.2.1            py38hbcfaee0_1
curl                      7.75.0               h06286d4_0    conda-forge
cycler                    0.10.0                   py38_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
descartes                 1.1.0                      py_4    conda-forge
docutils                  0.16                     pypi_0    pypi
entrypoints               0.3                      py38_0
expat                     2.2.10               h1c7c35f_0    conda-forge
fiona                     1.8.18                   pypi_0    pypi
flask                     1.1.1                      py_1
flask-httpauth            3.3.0                    pypi_0    pypi
folium                    0.12.0             pyhd8ed1ab_0    conda-forge
fontconfig                2.13.1            hd23ceaa_1004    conda-forge
freetype                  2.10.4               ha233b18_0
freexl                    1.0.5             h0b31af3_1002    conda-forge
gast                      0.3.3                    pypi_0    pypi
gdal                      3.2.1            py38hcd0f73a_8    conda-forge
geographiclib             1.50                       py_0    conda-forge
geohash                   1.0                      pypi_0    pypi
geopandas                 0.8.1                    pypi_0    pypi
geopy                     2.1.0              pyhd3deb0d_0    conda-forge
geos                      3.9.1                he49afe7_2    conda-forge
geotiff                   1.6.0                hba2ba3e_5    conda-forge
gettext                   0.19.8.1          h7937167_1005    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
google-auth               1.23.0                   pypi_0    pypi
google-auth-oauthlib      0.4.2                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
greenlet                  0.4.17           py38haf1e3a3_0
grpcio                    1.33.2                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hdf4                      4.2.13            h71d84a9_1004    conda-forge
hdf5                      1.10.6          nompi_h34ad4e8_1111    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
idna                      2.8                   py38_1000
importlib-metadata        2.0.0                      py_1
importlib_metadata        2.0.0                         1
intel-openmp              2019.4                      233
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.19.0           py38h01d92e1_0
ipython_genutils          0.2.0                    py38_0
itsdangerous              1.1.0                      py_0
jedi                      0.17.2                   py38_0
jinja2                    2.11.2                     py_0
joblib                    0.17.0                     py_0    anaconda
jpeg                      9d                   hbcb3906_0    conda-forge
json-c                    0.15                 hcb556a6_0    conda-forge
json5                     0.9.5                      py_0
jsonschema                3.2.0                      py_2
jupyter_client            6.1.7                      py_0
jupyter_core              4.6.3                    py38_0
jupyterlab                2.2.9                      py_0    conda-forge
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         1.2.0                      py_0
kealib                    1.4.14               h31dd65d_2    conda-forge
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.0            py38h23ab428_0
krb5                      1.17.2               h60d9502_0    conda-forge
lcms2                     2.11                 h92f6f08_0
libblas                   3.9.0           1_h43114d0_netlib    conda-forge
libcblas                  3.9.0           3_h7d47d6b_netlib    conda-forge
libcurl                   7.75.0               h8ef9fac_0    conda-forge
libcxx                    11.1.0               habf9029_0    conda-forge
libdap4                   3.20.6               h75eb3ff_1    conda-forge
libedit                   3.1.20191231         h1de35cc_1
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  hb1e8313_2
libgdal                   3.2.1                h0a7a322_8    conda-forge
libgfortran               4.0.0           7_5_0_h1a10cd1_19    conda-forge
libgfortran4              7.5.0               h1a10cd1_19    conda-forge
libglib                   2.66.7               hd556434_1    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libkml                    1.3.0             h3dc3bee_1012    conda-forge
liblapack                 3.9.0           3_h7d47d6b_netlib    conda-forge
libnetcdf                 4.7.4           nompi_h9d8a93f_107    conda-forge
libnghttp2                1.43.0               h07e645a_0    conda-forge
libpng                    1.6.37               ha441bb4_0
libpq                     13.1                 h052a64a_2    conda-forge
librttopo                 1.1.0                h4e44bc7_6    conda-forge
libsodium                 1.0.18               h1de35cc_0
libspatialindex           1.9.3                h1c7c35f_3    conda-forge
libspatialite             5.0.1                heb715ac_4    conda-forge
libssh2                   1.9.0                h52ee1ee_6    conda-forge
libtiff                   4.2.0                h355d032_0    conda-forge
libwebp-base              1.2.0                hbcf498f_0    conda-forge
libxgboost                1.2.0                hb1e8313_0    conda-forge
libxml2                   2.9.10               h802ca4f_3    conda-forge
llvm-openmp               11.0.0               h73239a0_1    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
markdown                  3.3.3                    pypi_0    pypi
markupsafe                1.1.1            py38h1de35cc_1
matplotlib                3.3.3            py38h50d1736_0    conda-forge
matplotlib-base           3.3.3            py38h9bfd75d_0    conda-forge
mistune                   0.8.4           py38h1de35cc_1001
mkl                       2019.4                      233
mkl-service               2.3.0            py38hfbe908c_0
mkl_fft                   1.2.0            py38hc64f4ea_0
mkl_random                1.1.1            py38h959d312_0
msgpack-python            1.0.0            py38h04f5b5a_1
munch                     2.5.0                      py_0    conda-forge
nbclient                  0.5.1                      py_0
nbconvert                 6.0.7                    py38_0
nbformat                  5.0.8                      py_0
ncurses                   6.2                  h0a44026_1
neovim                    0.3.1            py38h32f6830_2    conda-forge
nest-asyncio              1.4.2              pyhd3eb1b0_0
networkx                  2.5                        py_0    conda-forge
notebook                  6.1.4                    py38_0
numpy                     1.18.5                   pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                       py_0
openjpeg                  2.4.0                h6cbf5cd_0    conda-forge
openssl                   1.1.1j               hbcf498f_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
osmnx                     1.0.1              pyhd3deb0d_0    conda-forge
packaging                 20.4                       py_0
pandas                    0.25.3           py38h0a44026_0
pandoc                    2.11                 h0dc7051_0
pandocfilters             1.4.3            py38hecd8cb5_1
parso                     0.7.0                      py_0
patsy                     0.5.1                    py38_0
pcre                      8.44                 hb1e8313_0    conda-forge
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5                 py38_1001
pillow                    8.0.1            py38h5270095_0
pip                       20.2.4           py38hecd8cb5_0
pixman                    0.40.0               hbcb3906_0    conda-forge
poppler                   0.89.0               hd735947_5    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                13.1                 ha63e576_2    conda-forge
proj                      8.0.0                h1512c50_0    conda-forge
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.8                      py_0
protobuf                  3.14.0                   pypi_0    pypi
ptyprocess                0.6.0              pyhd3eb1b0_2
py-xgboost                1.2.0            py38h32f6830_0    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                       py_2
pydantic                  1.4              py38h1de35cc_0
pygments                  2.7.2              pyhd3eb1b0_0
pymongo                   3.9.0            py38h0a44026_0
pynvim                    0.4.2            py38h32f6830_1    conda-forge
pyopenssl                 19.1.0             pyhd3eb1b0_1
pyparsing                 2.4.7                      py_0
pyproj                    3.0.0.post1              pypi_0    pypi
pyrsistent                0.17.3           py38haf1e3a3_0
pysocks                   1.7.1                    py38_1
python                    3.8.5                h26836e1_1
python-dateutil           2.8.1                      py_0
python-dotenv             0.13.0                   pypi_0    pypi
python-geohash            0.8.5            py38h11c0d25_2    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1                     py_0
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.2           py38hb1e8313_1
readline                  8.0                  h1de35cc_0
requests                  2.22.0                   py38_1
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.6                      pypi_0    pypi
rtree                     0.9.7            py38hc59ffc2_1    conda-forge
scikit-learn              0.23.2           py38h959d312_0    anaconda
scipy                     1.4.1            py38h38b60c6_3    conda-forge
send2trash                1.5.0                    py38_0
setuptools                50.3.1           py38hecd8cb5_1
shapely                   1.7.1            py38h08f9a40_4    conda-forge
six                       1.15.0           py38hecd8cb5_0
sqlite                    3.34.0               h17101e1_0    conda-forge
statsmodels               0.12.0           py38haf1e3a3_0
tensorboard               2.4.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                2.3.1                    pypi_0    pypi
tensorflow-docs           0.0.01570ea4df9a2577e180d4e55a445d114c43cdfe0-          pypi_0    pypi
tensorflow-estimator      2.3.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.1                    py38_0
testpath                  0.4.4                      py_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
tiledb                    2.2.4                hddf8d7a_1    conda-forge
tk                        8.6.10               hb0a8c7a_0
tornado                   6.0.4            py38h1de35cc_1
traitlets                 5.0.5                      py_0
tzcode                    2021a                h0d85af4_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.25.11                    py_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
werkzeug                  1.0.1                      py_0
wheel                     0.35.1             pyhd3eb1b0_0
wrapt                     1.12.1                   pypi_0    pypi
xerces-c                  3.2.3                hd3a8c1e_2    conda-forge
xgboost                   1.2.0            py38h11c0d25_0    conda-forge
xz                        5.2.5                h1de35cc_0
zeromq                    4.3.3                hb1e8313_3
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h1de35cc_3
zstd                      1.4.9                h582d3a0_0    conda-forge
```
</details>

**Provide a complete minimal reproducible example**

Your example code snippet here must be *minimal* so it doesn't contain extraneous code unrelated to your specific problem and it must be *complete* so we can independently run it from top to bottom by copying/pasting it into a Python interpreter. That means all imports and all variables must be defined. If you're unsure how to create a good reproducible example, read [this guide](https://stackoverflow.com/help/minimal-reproducible-example). Do not post a screenshot of your code or error message: provide it as text.

```python
import osmnx as ox
ox.geometries.geometries_from_point((55.676098, 12.568337), tags={'amenity': True}, dist=250)
```

Trying to run lines 112-118 in [geometries.py](https://github.com/gboeing/osmnx/blob/master/osmnx/geometries.py) 

```
north, south, east, west = ox.utils_geo.bbox_from_point((55.676098, 12.568337), 250)
ox.utils_geo.bbox_to_poly(north, south, east, west)
polygon = ox.utils_geo.bbox_to_poly(north, south, east, west)
gdf = ox.geometries.geometries_from_polygon(polygon, tags={'amenity': True})
```
yields the same error for validation (line 252). Also, trying just to view the polygon created with `ox.utils_geo.bbox_to_poly(north, south, east, west)` yields a failed to evaluate error from `shapely`.

**Comment by AtelierLibre** [comment] 2021-03-12 12:30
I appreciate this doesn't necessarily help you out immediately, but I have just run your example in a new environment:

- Ubuntu 20.04
- Python 3.85
- OSMnx 1.0.1
- Shapely 1.7.1

and I can't replicate the error that you are seeing.

**Comment by gboeing** [comment] 2021-03-12 18:24
Hi @TMorville thanks for flagging this. Unfortunately, similar to @AtelierLibre, I'm unable to reproduce it. My best guess is that there's a dependency conflict somewhere under the hood in your environment, probably with geos. I might recommend removing your OSMnx environment and reinstalling it.

FWIW I'm using the same versions of shapely and geos as you are, but my builds of them have different hashes, which could account for our differences. I am on Python 3.9 on Ubuntu focal.

**Comment by gboeing** [comment] 2021-03-12 18:25
Hi @TMorville thanks for flagging this. Unfortunately, similar to @AtelierLibre, I'm unable to reproduce it. My best guess is that there's a dependency conflict somewhere under the hood in your environment, probably with geos. I might recommend removing your OSMnx environment and reinstalling it.

FWIW I'm using the same versions of shapely and geos as you are, but my builds of them have different hashes, which could account for our differences. I am on Python 3.9 on Ubuntu focal.

**Comment by gboeing** [comment] 2021-03-20 04:41
I'm going to close this for now as it seems to be unreproducible. If it becomes reproducible we can take another look.

**Closed by gboeing** 2021-03-20 04:41 UTC
Labels: bug
