### ISSUE TITLE
Trouble installing on OSX

### ISSUE THREAD

**Issue by JasonSanchez** [gboeing/osmnx#25] opened 2017-01-15 07:35 UTC
Your library looks amazing and I am excited to try it out. Unfortunately, the installation procedure produced an import error (included below).

Here were the exact steps I followed:

1. Uninstalled anaconda.
2. Reinstalled anaconda (Anaconda3-4.2.0-MacOSX-x86_64.pkg)
3. Ran `conda install -c conda-forge osmnx` in the terminal
4. Launched a Jupyter notebook (`jupyter notebook`)
5. Ran `import osmnx as ox`

System info:
OS X El Capitan v10.11.6
MacBook Pro

Complete stack trace:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a592ff119e79> in <module>()
----> 1 import osmnx as ox

/Users/user/anaconda/lib/python3.5/site-packages/osmnx/__init__.py in <module>()
      6 ###################################################################################################
      7 
----> 8 from .core import *
      9 from .plot import *
     10 from .projection import *

/Users/user/anaconda/lib/python3.5/site-packages/osmnx/core.py in <module>()
     18 import numpy as np
     19 import pandas as pd
---> 20 import geopandas as gpd
     21 import networkx as nx
     22 

/Users/user/anaconda/lib/python3.5/site-packages/geopandas/__init__.py in <module>()
      2 from geopandas.geodataframe import GeoDataFrame
      3 
----> 4 from geopandas.io.file import read_file
      5 from geopandas.io.sql import read_postgis
      6 from geopandas.tools import sjoin

/Users/user/anaconda/lib/python3.5/site-packages/geopandas/io/file.py in <module>()
      1 import os
      2 
----> 3 import fiona
      4 import numpy as np
      5 from shapely.geometry import mapping

/Users/user/anaconda/lib/python3.5/site-packages/fiona/__init__.py in <module>()
     67 from six import string_types
     68 
---> 69 from fiona.collection import Collection, BytesCollection, vsi_path
     70 from fiona._drivers import driver_count, GDALEnv
     71 from fiona.drvsupport import supported_drivers

/Users/user/anaconda/lib/python3.5/site-packages/fiona/collection.py in <module>()
      6 
      7 from fiona import compat
----> 8 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
      9 from fiona.ogrext import Session, WritingSession
     10 from fiona.ogrext import (

ImportError: dlopen(/Users/user/anaconda/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libnetcdf.11.dylib
  Referenced from: /Users/user/anaconda/lib/libgdal.20.dylib
  Reason: Incompatible library version: libgdal.20.dylib requires version 12.0.0 or later, but libnetcdf.11.dylib provides version 11.0.0

**Comment by gboeing** [comment] 2017-01-17 04:57
Can you open a new terminal window or Jupyter notebook and then run this line of Python code:

```Python
from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
```

From your trace, it looks like it's a problem with Fiona and your installed GDAL version. If the above Fiona import line does indeed fail, you'll want to open an issue at the Fiona repo because it looks like the problem is with that dependency. I don't have a Mac so I'm not sure I can reproduce this error.

**Comment by sgillies** [comment] 2017-01-17 07:53
@JasonSanchez @gboeing this is an Anaconda or conda-forge packaging issue. There's nothing the Fiona project can do to solve it.

**Comment by gboeing** [comment] 2017-01-17 17:19
Thanks @sgillies, good point - looks like a conda-forge issue.

**Comment by gboeing** [comment] 2017-01-17 17:26
@JasonSanchez you might want to isolate the nature of this problem by creating a clean virtual environment, then installing Fiona via conda-forge. If that succeeds, then create a clean virtual environment and install geopandas via conda-forge. If that succeeds, then create a clean virtual environment and install osmnx via conda-forge.

If one fails, you might open an issue with the relevant conda-forge feedstock. At some point, using a clean virtual env will either solve the problem or will give you an idea of which conda-forge package installation is having trouble on Mac. If it remains a problem you'll need to track it down with the relevant conda-forge feedstock.

In the meantime, you can install osmnx with pip, in whole or in part.

**Comment by ocefpaf** [comment] 2017-01-17 17:27
> Thanks @sgillies, good point - looks like a conda-forge issue.

Indeed. Please report it at https://github.com/conda-forge/osmnx-feedstock/issues

However, it does seems like you are mixing packages from `defaults` and `conda-forge`. If you isolate that in an env it should be OK.

```shell
conda create --yes -c conda-forge -n OSMNX python=3.6 osmnx
source activate OSMNX
python -c 'import osmnx'
```

**Comment by sgillies** [comment] 2017-01-17 17:44
@ocefpaf that was my suspicion, too.

**Comment by JasonSanchez** [comment] 2017-01-18 05:57
Wow! The snippet posted by @ocefpaf worked perfectly! Thank you all so much for your help and for making it possible for me to use such an awesome library!

**Comment by khibma** [comment] 2017-01-18 14:36
@ocefpaf +1 - I encountered this too. Thanks for the suggestion.

**Comment by JasonSanchez** [comment] 2017-02-06 09:32
Hi all, although everything was working, now it is broken again with a different error. I tried incredibly hard to solve the issue by myself and ended up spending several hours with no luck. Running the snippet from @ocefpaf on a clean install of Anaconda generates the following error:
```
MacBook-Pro-5:~ Jason$ python -c 'import osmnx; print(osmnx.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user/anaconda/envs/OSMNX1/lib/python3.6/site-packages/osmnx/__init__.py", line 8, in <module>
    from .core import *
  File "/Users/user/anaconda/envs/OSMNX1/lib/python3.6/site-packages/osmnx/core.py", line 20, in <module>
    import geopandas as gpd
  File "/Users/user/anaconda/envs/OSMNX1/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/Users/user/anaconda/envs/OSMNX1/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/Users/user/anaconda/envs/OSMNX1/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/Users/user/anaconda/envs/OSMNX1/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/user/anaconda/envs/OSMNX1/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libicui18n.56.dylib
  Referenced from: /Users/user/anaconda/envs/OSMNX1/lib/libgdal.20.dylib
  Reason: image not found
```

At this point I will try pretty much anything to get it working again. I would very much appreciate your help in pointing me in the right direction.

**Comment by undecidedfellow** [comment] 2017-02-10 16:51
I also have this problem

**Comment by ocefpaf** [comment] 2017-02-10 16:57
Please open issues related to the conda package at: https://github.com/conda-forge/osmnx-feedstock/issues

I recommend to check your `.condarc` file and ensure that the `conda-forge` channel is on top of `defaults` before trying https://github.com/gboeing/osmnx/issues/25#issuecomment-273237748 again.

**Comment by gboeing** [comment] 2017-02-12 18:51
Thanks @ocefpaf. As this is an issue with conda installation rather than with the OSMnx codebase itself, I'm going to close this here. For future reference, if anyone has this problem please open an issue at https://github.com/conda-forge/osmnx-feedstock/issues

**Closed by gboeing** 2017-02-12 18:51 UTC

**Comment by gboeing** [comment] 2017-02-26 00:26
For future reference, see https://github.com/conda-forge/osmnx-feedstock/issues/14
