### ISSUE TITLE
Buffer distance should be flexible in the function graph_from_polygon() by adding parameter in file 'osmnx/graph.py': parameter 'buffer_dist' should be added in the list of parameters of function graph_from_polygon() so that flexible buffer distance can be specified.

### ISSUE THREAD

**Issue by Prajwalita** [gboeing/osmnx#952] opened 2023-05-15 11:42 UTC
**Original function:**

 def graph_from_polygon(
    polygon,
    network_type="all_private",
    simplify=True,
    retain_all=False,
    truncate_by_edge=False,
    clean_periphery=True,
    custom_filter=None,
):
 """
    Create a graph from OSM within the boundaries of some shapely polygon.

    Parameters
    ----------
    polygon : shapely.geometry.Polygon or shapely.geometry.MultiPolygon
        the shape to get network data within. coordinates should be in
        unprojected latitude-longitude degrees (EPSG:4326).
    network_type : string {"all_private", "all", "bike", "drive", "drive_service", "walk"}
        what type of street network to get if custom_filter is None
    simplify : bool
        if True, simplify graph topology with the `simplify_graph` function
    retain_all : bool
        if True, return the entire graph even if it is not connected.
        otherwise, retain only the largest weakly connected component.
    truncate_by_edge : bool
        if True, retain nodes outside boundary polygon if at least one of
        node's neighbors is within the polygon
    clean_periphery : bool
        if True, buffer 500m to get a graph larger than requested, then
        simplify, then truncate it to requested spatial boundaries
    custom_filter : string
        a custom ways filter to be used instead of the network_type presets
        e.g., '["power"~"line"]' or '["highway"~"motorway|trunk"]'. Also pass
        in a network_type that is in settings.bidirectional_network_types if
        you want graph to be fully bi-directional.

    Returns
    -------
    G : networkx.MultiDiGraph

   Notes
    -----
    You can configure the Overpass server timeout, memory allocation, and
    other custom settings via the `settings` module. Very large query areas
    will use the utils_geo._consolidate_subdivide_geometry function to perform
    multiple queries: see that function's documentation for caveats.
    """

**Suggested Feature proposal:**

def graph_from_polygon(
    polygon,
    network_type="all_private",
    simplify=True,
    retain_all=False,
    truncate_by_edge=False,
    clean_periphery=True,
    **buffer_dist=None,**
    custom_filter=None,
):

 """
    Create a graph from OSM within the boundaries of some shapely polygon.

    Parameters
    ----------
    polygon : shapely.geometry.Polygon or shapely.geometry.MultiPolygon
        the shape to get network data within. coordinates should be in
        unprojected latitude-longitude degrees (EPSG:4326).
    network_type : string {"all_private", "all", "bike", "drive", "drive_service", "walk"}
        what type of street network to get if custom_filter is None
    simplify : bool
        if True, simplify graph topology with the `simplify_graph` function
    retain_all : bool
        if True, return the entire graph even if it is not connected.
        otherwise, retain only the largest weakly connected component.
    truncate_by_edge : bool
        if True, retain nodes outside boundary polygon if at least one of
        node's neighbors is within the polygon
    clean_periphery : bool
        if True, buffer 500m to get a graph larger than requested, then
        simplify, then truncate it to requested spatial boundaries
    **buffer_dist : float
       distance to buffer around the place geometry, in meters by default buffer 500m**
    custom_filter : string
        a custom ways filter to be used instead of the network_type presets
        e.g., '["power"~"line"]' or '["highway"~"motorway|trunk"]'. Also pass
        in a network_type that is in settings.bidirectional_network_types if
        you want graph to be fully bi-directional.

    Returns
    -------
    G : networkx.MultiDiGraph

    Notes
    -----
    You can configure the Overpass server timeout, memory allocation, and
    other custom settings via the `settings` module. Very large query areas
    will use the utils_geo._consolidate_subdivide_geometry function to perform
    multiple queries: see that function's documentation for caveats.
    """

**Read these instructions carefully. Use the template below and fill out every section. Your issue will be automatically closed if you don't provide all of the information requested in the template, because we need this information to address your issue. Before you proceed, review the contributing guidelines in the CONTRIBUTING.md file.**

Feature requests are for proposing an enhancement to OSMnx before opening a pull request to add your proposed functionality to the codebase. Please don't use the issue tracker to ask "how-to" or usage questions. If asked here, they will be closed automatically. Instead, ask "how-to" and usage questions on [StackOverflow](https://stackoverflow.com/search?q=osmnx).

**Do not delete the following template. Fill it out completely.**

  - [ ] I have read the OSMnx [contributing guidelines](../blob/main/CONTRIBUTING.md)
  - [ ] I have read the OSMnx [documentation](https://osmnx.readthedocs.io/) and [usage examples](https://github.com/gboeing/osmnx-examples)
  - [ ] I have searched the open/closed issues and pull requests for others similar to mine

**Is your feature proposal related to a problem?**

A clear and concise description of what the problem is.

**Describe the solution you'd like to propose**

A clear and concise description of what you want to change in OSMnx and how you plan to implement it.

**Describe alternatives you've considered**

**Additional context**

Provide a complete minimal working example of code to demonstrate your use case. Add any additional code snippets, context, or screenshots about the feature proposal to demonstrate its importance and feasibility.

**Comment by gboeing** [comment] 2023-05-15 15:59
Duplicate of #943, and as stated there:

> Thanks for using OSMnx! Please fill out the complete feature proposal template to help us understand the nature of the problem, the details of your proposed solution, the alternatives you considered, and any additional context, including code to demonstrate your use case and its importance and feasibility.

The nature of the problem remains unstated, and there are still no details regarding the use case and its importance, why/how this proposed solution solves an important problem, or what alternatives were under consideration.

Even if you adjust the `buffer_dist` value, you will still get the same resulting graph in the end. The parameter merely ensures you get accurate connectivity details for the nodes on the periphery. This does not give you a buffered graph as a result, it just allows OSMnx to download surrounding data to inspect what's just beyond the desired periphery to add correct metadata to peripheral nodes, as described in the [documentation](https://osmnx.readthedocs.io/en/stable/osmnx.html#module-osmnx.stats):

> If clean_periphery=True when the graph was created (which is the default parameterization), then you will get accurate node degrees (and in turn streets-per-node counts) even at the periphery of the graph.

If you have usage questions about this function (beyond the documentation and usage examples), please ask on StackOverflow, per the contributing guidelines. Thanks.

**Closed by gboeing** 2023-05-15 15:59 UTC
Labels: enhancement

**Comment by xiaoyangdemingren** [comment] 2024-05-05 05:54
It would be of great use when we want to merge data after get road network from two near polygenes, still a problem unsolved

**Comment by Prajwalita** [comment] 2024-05-06 11:39
Similar functionality is available for the function graph_from_point(). But it is not available for def graph_from_polygon(). Here user can get buffer with fixed 500 meters. However the value of buffer is not flexible. My proposal is that we can also add one new parameter buffer_dist(float value) so that user can give any buffer value to create a graph with the buffer. Because I faced this problem while working on a government project.
I am sending push request for this update. Please review my proposal.
